<a id='Import_Library'></a>
## **1. Import Libraries** ##

In [1]:
import pandas as pd
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive

<a id='Query_KOI_Data_from_Exoplanet_Archive'></a>
## **2. Query KOI Data from Exoplanet Archive** ##

In [4]:
# Select pre-computed features
columns = ['kepid', 'kepoi_name', 'kepler_name', 'ra', 'dec', 'koi_kepmag', 'koi_disposition', 'koi_score', 'koi_fpflag_nt', 
           'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec',
           'koi_period', 'koi_time0bk', 'koi_duration', 'koi_depth', 'koi_model_snr', 'koi_impact', 'koi_prad', 'koi_teq', 'koi_insol', 'koi_ror', 
           'koi_steff', 'koi_slogg', 'koi_srad', 'koi_smass']

# Query the q1_q17_dr25_koi table for confirmed exoplanets and false positives
koi_table = NasaExoplanetArchive.query_criteria(
    table="q1_q17_dr25_koi",
    where="koi_disposition like '%CONFIRMED%' or koi_disposition like '%FALSE POSITIVE%' or koi_disposition like '%CANDIDATE%'",
    select=columns,
    order="kepler_name",
    cache=True,
)

# Convert to pandas DataFrame
koi_df = koi_table.to_pandas()

# Save the DataFrame to a CSV file
koi_df.to_csv('data\\kepler_objects_of_interset(kois).csv', index=False)

print("Data saved to 'data/kepler_objects_of_interset(kois)'.")
print(koi_df)

Data saved to 'data/kepler_objects_of_interset(kois)'.
         kepid kepoi_name   kepler_name         ra        dec  koi_kepmag  \
0     11446443  K00001.01    Kepler-1 b  286.80847  49.316399      11.338
1     11904151  K00072.01   Kepler-10 b  285.67938  50.241299      10.961
2     11904151  K00072.02   Kepler-10 c  285.67938  50.241299      10.961
3      6521045  K00041.02  Kepler-100 b  291.38599  41.990269      11.197
4      6521045  K00041.01  Kepler-100 c  291.38599  41.990269      11.197
...        ...        ...           ...        ...        ...         ...
8049   4752451  K00109.01                293.45428  39.803928      12.385
8050   9053112  K00702.01                300.72702  45.305538      13.759
8051   9162741  K00703.01                294.91202  45.566685      13.361
8052   9300285  K00705.01                298.45319  45.746101      13.788
8053   9426071  K00706.01                299.28305  45.964439      13.765

     koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  ...  koi_prad  \
0          CONFIRMED      0.811              0              0  ...     13.04
1          CONFIRMED      0.000              1              0  ...      1.43
2          CONFIRMED      0.982              0              0  ...      2.26
3          CONFIRMED      1.000              0              0  ...      1.30
4          CONFIRMED      1.000              0              0  ...      2.26
...              ...        ...            ...            ...  ...       ...
8049  FALSE POSITIVE      0.000              0              1  ...     25.79
8050  FALSE POSITIVE      0.000              0              1  ...     66.76
8051  FALSE POSITIVE      0.000              0              0  ...      1.84
8052  FALSE POSITIVE      0.000              0              0  ...      5.89
8053  FALSE POSITIVE      0.000              0              1  ...     42.19

      koi_teq  koi_insol   koi_ror  koi_steff  koi_slogg  koi_srad  koi_smass  \
0      1339.0     761.46  0.123871     5820.0      4.457     0.964      0.971
1      1980.0    3630.32  0.012545     5676.0      4.347     1.044      0.884
2       524.0      17.75  0.019806     5676.0      4.347     1.044      0.884
3      1155.0     420.97  0.008082     5788.0      4.122     1.474      1.050
4       939.0     183.68  0.014067     5788.0      4.122     1.474      1.050
...       ...        ...       ...        ...        ...       ...        ...
8049   1153.0     417.97  0.199610     6170.0      4.259     1.183      0.927
8050   2498.0    9187.90  0.212870     5365.0      3.669     2.872      1.403
8051   2255.0    6108.26  0.010622     6561.0      4.140     1.584      1.272
8052   2337.0    7026.31  0.040293     6663.0      4.275     1.338      1.235
8053    794.0      93.74  0.272653     6706.0      4.226     1.417      1.240

      sky_coord.ra  sky_coord.dec
0        286.80847      49.316399
1        285.67938      50.241299
2        285.67938      50.241299
3        291.38599      41.990269
4        291.38599      41.990269
...            ...            ...
8049     293.45428      39.803928
8050     300.72702      45.305538
8051     294.91202      45.566685
8052     298.45319      45.746101
8053     299.28305      45.964439

[8054 rows x 28 columns]

In [5]:
# Query the keplernames table for confirmed names of planets
# This table contains the kepler names and confirmed names of planets
koi_confirmed_planets_table = NasaExoplanetArchive.query_criteria(
    table="keplernames",
    select="kepid, kepler_name, pl_name",
    order="kepler_name",
    cache=True,
)

# Convert to pandas DataFrame
koi_confirmed_planets_df = koi_confirmed_planets_table.to_pandas()

# Save the DataFrame to a CSV file
koi_confirmed_planets_df.to_csv('data\\kepler_confirmed_planet_names.csv', index=False)

print("Data saved to 'data/kepler_confirmed_names'.")
print(koi_confirmed_planets_df)

Data saved to 'data/kepler_confirmed_names'.
         kepid   kepler_name       pl_name
0     11446443    Kepler-1 b      TrES-2 b
1     11904151   Kepler-10 b   Kepler-10 b
2     11904151   Kepler-10 c   Kepler-10 c
3     11904151   Kepler-10 d   Kepler-10 d
4      6521045  Kepler-100 b  Kepler-100 b
...        ...           ...           ...
2811   4035640  Kepler-995 b  Kepler-995 b
2812   6205228  Kepler-996 b  Kepler-996 b
2813  11758544  Kepler-997 b  Kepler-997 b
2814  11413812  Kepler-998 b  Kepler-998 b
2815   9549648  Kepler-999 b  Kepler-999 b

[2816 rows x 3 columns]

In [6]:
# Select pre-computed features
columns = ['pl_name', 'hostname', 'disc_year', 'discoverymethod', 'tran_flag', 'disc_facility', 'disc_telescope', 
           'disc_instrument', 
           'pl_orbper', 'pl_rade', 'pl_masse', 'pl_dens', 'pl_insol', 'pl_imppar', 'pl_trandep', 
           'st_teff', 'st_rad', 'st_mass', 'st_lum', 'st_age', 'st_dens']

# Query the Planetary Systems table for confirmed exoplanets discovered via the transit method.
# Specifically, filter results to include only those discovered by the Kepler mission,
# by ensuring that the discovery facility, telescope (0.95 m Kepler Telescope), and instrument (Kepler CCD Array) all include 'Kepler'.
# Results are ordered by the year of discovery.

planetory_systems_table = NasaExoplanetArchive.query_criteria(
    table="pscomppars",
    select=columns,
    where="discoverymethod like '%Transit%' and tran_flag = '1' and disc_facility like '%Kepler%' and disc_telescope like '%Kepler%' and disc_instrument like '%Kepler%'",
    order="disc_year",
    cache=True,
)

# Convert to pandas DataFrame
planetory_systems_df = planetory_systems_table.to_pandas()

# Save the DataFrame to a CSV file
planetory_systems_df.to_csv('data\\planetory_systems.csv', index=False)

print("Data saved to 'data/planetory_systems'.")
print(planetory_systems_df)

Data saved to 'data/planetory_systems'.
           pl_name    hostname  disc_year discoverymethod  tran_flag  \
0       Kepler-5 b    Kepler-5       2009         Transit          1
1       Kepler-6 b    Kepler-6       2009         Transit          1
2       Kepler-4 b    Kepler-4       2009         Transit          1
3       Kepler-7 b    Kepler-7       2009         Transit          1
4       Kepler-9 b    Kepler-9       2010         Transit          1
...            ...         ...        ...             ...        ...
2756    KOI-4978 b    KOI-4978       2024         Transit          1
2757  Kepler-963 c  Kepler-963       2024         Transit          1
2758  Kepler-289 e  Kepler-289       2025         Transit          1
2759  Kepler-279 e  Kepler-279       2025         Transit          1
2760     KOI-134 b     KOI-134       2025         Transit          1

     disc_facility           disc_telescope   disc_instrument   pl_orbper  \
0           Kepler  0.95 m Kepler Telescope  Kepler CCD Array    3.548466
1           Kepler  0.95 m Kepler Telescope  Kepler CCD Array    3.234700
2           Kepler  0.95 m Kepler Telescope  Kepler CCD Array    3.213460
3           Kepler  0.95 m Kepler Telescope  Kepler CCD Array    4.885489
4           Kepler  0.95 m Kepler Telescope  Kepler CCD Array   19.238910
...            ...                      ...               ...         ...
2756        Kepler  0.95 m Kepler Telescope  Kepler CCD Array    0.941967
2757        Kepler  0.95 m Kepler Telescope  Kepler CCD Array    0.919783
2758        Kepler  0.95 m Kepler Telescope  Kepler CCD Array  330.071600
2759        Kepler  0.95 m Kepler Telescope  Kepler CCD Array   98.353100
2760        Kepler  0.95 m Kepler Telescope  Kepler CCD Array   67.127700

        pl_rade  ...  pl_dens  pl_insol  pl_imppar  pl_trandep  st_teff  \
0     15.984034  ...     0.40  1822.758     0.0968     0.72515  6297.00
1     14.616536  ...     0.40   792.218     0.1410     1.08141  5647.00
2      4.002000  ...     1.91  1245.431     0.0220     0.08700  5857.00
3     18.180998  ...     0.14  1375.110     0.5599     0.75693  5933.00
4      8.290000  ...     0.42    48.229     0.5900     0.66605  5774.00
...         ...  ...      ...       ...        ...         ...      ...
2756   0.700000  ...     4.34       NaN        NaN         NaN  5050.28
2757   0.600000  ...     3.97       NaN        NaN         NaN  5169.47
2758   2.940000  ...     2.92     1.580     0.6800     0.06167  5990.00
2759   4.130000  ...     7.30    21.960     0.9100     0.04230  6689.45
2760  12.038445  ...     1.09    45.000     0.3860     0.52759  6160.00

      st_rad  st_mass   st_lum  st_age  st_dens
0      1.793    1.374  0.65242    2.88  0.39897
1      1.391    1.209  0.18916    3.80  0.77551
2      1.487    1.223  0.35400    4.50  0.46728
3      1.966    1.359  0.69639    2.90  0.32016
4      0.958    1.022 -0.03800    2.00  1.64000
...      ...      ...      ...     ...      ...
2756   0.966    0.859 -0.17690    1.48  1.10000
2757   0.928    0.821 -0.22463   13.20  3.20000
2758   0.985    1.061  0.06100    0.65  1.91026
2759   1.430    1.164  0.51880    0.22  0.04350
2760   1.667    1.407  0.62325    2.40  1.32000

[2761 rows x 21 columns]

In [7]:
# Import CSV files into pandas DataFrames
kois_df = pd.read_csv('data\\kepler_objects_of_interset(kois).csv') # Load Kepler Objects of Interest (KOIs) data
kepler_confirmed_planet_names_df = pd.read_csv('data\\kepler_confirmed_planet_names.csv') # Load confirmed Kepler planet names data
planetory_systems_df = pd.read_csv('data\\planetory_systems.csv') # Load planetary systems data

# Merge kois_df and kepler_confirmed_planet_names_df DataFrames on 'kepid' and 'kepler_name' using a left join
confirmed_kois_df = pd.merge(kois_df, kepler_confirmed_planet_names_df, on=['kepid', 'kepler_name'], how='left')
print(confirmed_kois_df)

# Remove rows where:
# 1. koi_disposition is 'CONFIRMED' but kepler_name is null
# 2. koi_disposition is 'FALSE_POSITIVE' but has a kepler_name
# 3. koi_disposition is 'CANDIDATE' but has a kepler_name

#confirmed_kois_df = confirmed_kois_df[~(((confirmed_kois_df['koi_disposition'] == 'CONFIRMED') & (confirmed_kois_df['kepler_name'].isnull())) | ((confirmed_kois_df['koi_disposition'] == 'FALSE POSITIVE') & (confirmed_kois_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))]

#confirmed_kois_df = confirmed_kois_df.drop(confirmed_kois_df[(((confirmed_kois_df['koi_disposition'] == 'CONFIRMED') & (confirmed_kois_df['kepler_name'].isnull())) | ((confirmed_kois_df['koi_disposition'] == 'FALSE POSITIVE') & (confirmed_kois_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))].index)

confirmed_kois_df.drop(confirmed_kois_df[(((confirmed_kois_df['koi_disposition'] == 'CONFIRMED') & (confirmed_kois_df['kepler_name'].isnull())) | ((confirmed_kois_df['koi_disposition'] == 'FALSE POSITIVE') & (confirmed_kois_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))].index, inplace=True)
print(confirmed_kois_df)

# Merge confirmed_kois_df with planetory_systems_df on 'pl_name' using a left join, including an indicator column
final_df = pd.merge(confirmed_kois_df, planetory_systems_df, on='pl_name', how='left', indicator=True)
print(final_df)

# Remove rows where:
# 1. koi_disposition is 'CONFIRMED' but no match in planetory_systems_df (_merge is 'left_only')
# 2. koi_disposition is 'FALSE POSITIVE' but has a kepler_name
# 3. koi_disposition is 'CANDIDATE' but has a kepler_name 

#final_df = final_df[~(((final_df['koi_disposition'] == 'CONFIRMED') & (final_df['_merge'] == 'left_only')) | ((final_df['koi_disposition'] == 'FALSE POSITIVE') & (final_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))]

#final_df = final_df.drop(final_df[(((final_df['koi_disposition'] == 'CONFIRMED') & (final_df['_merge'] == 'left_only')) | ((final_df['koi_disposition'] == 'FALSE POSITIVE') & (final_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))].index)

final_df.drop(final_df[(((final_df['koi_disposition'] == 'CONFIRMED') & (final_df['_merge'] == 'left_only')) | 
              ((final_df['koi_disposition'] == 'FALSE POSITIVE') & (final_df['kepler_name'].notnull())) | ((confirmed_kois_df['koi_disposition'] == 'CANDIDATE') & (confirmed_kois_df['kepler_name'].notnull())))].index, inplace=True)

final_df.to_csv('data/final_df.csv', index=False)
print(final_df)

         kepid kepoi_name   kepler_name         ra        dec  koi_kepmag  \
0     11446443  K00001.01    Kepler-1 b  286.80847  49.316399      11.338
1     11904151  K00072.01   Kepler-10 b  285.67938  50.241299      10.961
2     11904151  K00072.02   Kepler-10 c  285.67938  50.241299      10.961
3      6521045  K00041.02  Kepler-100 b  291.38599  41.990269      11.197
4      6521045  K00041.01  Kepler-100 c  291.38599  41.990269      11.197
...        ...        ...           ...        ...        ...         ...
8049   4752451  K00109.01           NaN  293.45428  39.803928      12.385
8050   9053112  K00702.01           NaN  300.72702  45.305538      13.759
8051   9162741  K00703.01           NaN  294.91202  45.566685      13.361
8052   9300285  K00705.01           NaN  298.45319  45.746101      13.788
8053   9426071  K00706.01           NaN  299.28305  45.964439      13.765

     koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  ...  koi_teq  \
0          CONFIRMED      0.811              0              0  ...   1339.0
1          CONFIRMED      0.000              1              0  ...   1980.0
2          CONFIRMED      0.982              0              0  ...    524.0
3          CONFIRMED      1.000              0              0  ...   1155.0
4          CONFIRMED      1.000              0              0  ...    939.0
...              ...        ...            ...            ...  ...      ...
8049  FALSE POSITIVE      0.000              0              1  ...   1153.0
8050  FALSE POSITIVE      0.000              0              1  ...   2498.0
8051  FALSE POSITIVE      0.000              0              0  ...   2255.0
8052  FALSE POSITIVE      0.000              0              0  ...   2337.0
8053  FALSE POSITIVE      0.000              0              1  ...    794.0

      koi_insol   koi_ror  koi_steff  koi_slogg  koi_srad  koi_smass  \
0        761.46  0.123871     5820.0      4.457     0.964      0.971
1       3630.32  0.012545     5676.0      4.347     1.044      0.884
2         17.75  0.019806     5676.0      4.347     1.044      0.884
3        420.97  0.008082     5788.0      4.122     1.474      1.050
4        183.68  0.014067     5788.0      4.122     1.474      1.050
...         ...       ...        ...        ...       ...        ...
8049     417.97  0.199610     6170.0      4.259     1.183      0.927
8050    9187.90  0.212870     5365.0      3.669     2.872      1.403
8051    6108.26  0.010622     6561.0      4.140     1.584      1.272
8052    7026.31  0.040293     6663.0      4.275     1.338      1.235
8053      93.74  0.272653     6706.0      4.226     1.417      1.240

      sky_coord.ra  sky_coord.dec       pl_name
0        286.80847      49.316399      TrES-2 b
1        285.67938      50.241299   Kepler-10 b
2        285.67938      50.241299   Kepler-10 c
3        291.38599      41.990269  Kepler-100 b
4        291.38599      41.990269  Kepler-100 c
...            ...            ...           ...
8049     293.45428      39.803928           NaN
8050     300.72702      45.305538           NaN
8051     294.91202      45.566685           NaN
8052     298.45319      45.746101           NaN
8053     299.28305      45.964439           NaN

[8054 rows x 29 columns]
         kepid kepoi_name   kepler_name         ra        dec  koi_kepmag  \
0     11446443  K00001.01    Kepler-1 b  286.80847  49.316399      11.338
1     11904151  K00072.01   Kepler-10 b  285.67938  50.241299      10.961
2     11904151  K00072.02   Kepler-10 c  285.67938  50.241299      10.961
3      6521045  K00041.02  Kepler-100 b  291.38599  41.990269      11.197
4      6521045  K00041.01  Kepler-100 c  291.38599  41.990269      11.197
...        ...        ...           ...        ...        ...         ...
8049   4752451  K00109.01           NaN  293.45428  39.803928      12.385
8050   9053112  K00702.01           NaN  300.72702  45.305538      13.759
8051   9162741  K00703.01           NaN  294.91202  45.566685      13.361
8052   9300285  K00705.01           NaN  298.45319  45.746101      13.788
8053   9426071  K00706.01           NaN  299.28305  45.964439      13.765

     koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  ...  koi_teq  \
0          CONFIRMED      0.811              0              0  ...   1339.0
1          CONFIRMED      0.000              1              0  ...   1980.0
2          CONFIRMED      0.982              0              0  ...    524.0
3          CONFIRMED      1.000              0              0  ...   1155.0
4          CONFIRMED      1.000              0              0  ...    939.0
...              ...        ...            ...            ...  ...      ...
8049  FALSE POSITIVE      0.000              0              1  ...   1153.0
8050  FALSE POSITIVE      0.000              0              1  ...   2498.0
8051  FALSE POSITIVE      0.000              0              0  ...   2255.0
8052  FALSE POSITIVE      0.000              0              0  ...   2337.0
8053  FALSE POSITIVE      0.000              0              1  ...    794.0

      koi_insol   koi_ror  koi_steff  koi_slogg  koi_srad  koi_smass  \
0        761.46  0.123871     5820.0      4.457     0.964      0.971
1       3630.32  0.012545     5676.0      4.347     1.044      0.884
2         17.75  0.019806     5676.0      4.347     1.044      0.884
3        420.97  0.008082     5788.0      4.122     1.474      1.050
4        183.68  0.014067     5788.0      4.122     1.474      1.050
...         ...       ...        ...        ...       ...        ...
8049     417.97  0.199610     6170.0      4.259     1.183      0.927
8050    9187.90  0.212870     5365.0      3.669     2.872      1.403
8051    6108.26  0.010622     6561.0      4.140     1.584      1.272
8052    7026.31  0.040293     6663.0      4.275     1.338      1.235
8053      93.74  0.272653     6706.0      4.226     1.417      1.240

      sky_coord.ra  sky_coord.dec       pl_name
0        286.80847      49.316399      TrES-2 b
1        285.67938      50.241299   Kepler-10 b
2        285.67938      50.241299   Kepler-10 c
3        291.38599      41.990269  Kepler-100 b
4        291.38599      41.990269  Kepler-100 c
...            ...            ...           ...
8049     293.45428      39.803928           NaN
8050     300.72702      45.305538           NaN
8051     294.91202      45.566685           NaN
8052     298.45319      45.746101           NaN
8053     299.28305      45.964439           NaN

[8051 rows x 29 columns]
         kepid kepoi_name   kepler_name         ra        dec  koi_kepmag  \
0     11446443  K00001.01    Kepler-1 b  286.80847  49.316399      11.338
1     11904151  K00072.01   Kepler-10 b  285.67938  50.241299      10.961
2     11904151  K00072.02   Kepler-10 c  285.67938  50.241299      10.961
3      6521045  K00041.02  Kepler-100 b  291.38599  41.990269      11.197
4      6521045  K00041.01  Kepler-100 c  291.38599  41.990269      11.197
...        ...        ...           ...        ...        ...         ...
8046   4752451  K00109.01           NaN  293.45428  39.803928      12.385
8047   9053112  K00702.01           NaN  300.72702  45.305538      13.759
8048   9162741  K00703.01           NaN  294.91202  45.566685      13.361
8049   9300285  K00705.01           NaN  298.45319  45.746101      13.788
8050   9426071  K00706.01           NaN  299.28305  45.964439      13.765

     koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  ...  pl_insol  \
0          CONFIRMED      0.811              0              0  ...       NaN
1          CONFIRMED      0.000              1              0  ...  3741.780
2          CONFIRMED      0.982              0              0  ...    18.300
3          CONFIRMED      1.000              0              0  ...   478.214
4          CONFIRMED      1.000              0              0  ...   208.657
...              ...        ...            ...            ...  ...       ...
8046  FALSE POSITIVE      0.000              0              1  ...       NaN
8047  FALSE POSITIVE      0.000              0              1  ...       NaN
8048  FALSE POSITIVE      0.000              0              0  ...       NaN
8049  FALSE POSITIVE      0.000              0              0  ...       NaN
8050  FALSE POSITIVE      0.000              0              1  ...       NaN

      pl_imppar  pl_trandep  st_teff  st_rad  st_mass   st_lum  st_age  \
0           NaN         NaN      NaN     NaN      NaN      NaN     NaN
1        0.3390     0.01919   5708.0   1.065     0.91  0.05467   10.60
2        0.3182     0.04768   5708.0   1.065     0.91  0.05467   10.60
3        0.5400     0.00739   5837.0   1.510     1.13  0.39445    6.92
4        0.0500     0.02181   5825.0   1.490     1.08  0.39445    6.46
...         ...         ...      ...     ...      ...      ...     ...
8046        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8047        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8048        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8049        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8050        NaN         NaN      NaN     NaN      NaN      NaN     NaN

      st_dens     _merge
0         NaN  left_only
1       1.068       both
2       1.068       both
3       0.440       both
4       0.440       both
...       ...        ...
8046      NaN  left_only
8047      NaN  left_only
8048      NaN  left_only
8049      NaN  left_only
8050      NaN  left_only

[8051 rows x 50 columns]

C:\Users\athar\AppData\Local\Temp\ipykernel_22248\2179318749.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_df.drop(final_df[(((final_df['koi_disposition'] == 'CONFIRMED') & (final_df['_merge'] == 'left_only')) |

         kepid kepoi_name   kepler_name         ra        dec  koi_kepmag  \
1     11904151  K00072.01   Kepler-10 b  285.67938  50.241299      10.961
2     11904151  K00072.02   Kepler-10 c  285.67938  50.241299      10.961
3      6521045  K00041.02  Kepler-100 b  291.38599  41.990269      11.197
4      6521045  K00041.01  Kepler-100 c  291.38599  41.990269      11.197
5      6521045  K00041.03  Kepler-100 d  291.38599  41.990269      11.197
...        ...        ...           ...        ...        ...         ...
8046   4752451  K00109.01           NaN  293.45428  39.803928      12.385
8047   9053112  K00702.01           NaN  300.72702  45.305538      13.759
8048   9162741  K00703.01           NaN  294.91202  45.566685      13.361
8049   9300285  K00705.01           NaN  298.45319  45.746101      13.788
8050   9426071  K00706.01           NaN  299.28305  45.964439      13.765

     koi_disposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  ...  pl_insol  \
1          CONFIRMED      0.000              1              0  ...  3741.780
2          CONFIRMED      0.982              0              0  ...    18.300
3          CONFIRMED      1.000              0              0  ...   478.214
4          CONFIRMED      1.000              0              0  ...   208.657
5          CONFIRMED      1.000              0              0  ...    53.981
...              ...        ...            ...            ...  ...       ...
8046  FALSE POSITIVE      0.000              0              1  ...       NaN
8047  FALSE POSITIVE      0.000              0              1  ...       NaN
8048  FALSE POSITIVE      0.000              0              0  ...       NaN
8049  FALSE POSITIVE      0.000              0              0  ...       NaN
8050  FALSE POSITIVE      0.000              0              1  ...       NaN

      pl_imppar  pl_trandep  st_teff  st_rad  st_mass   st_lum  st_age  \
1        0.3390     0.01919   5708.0   1.065     0.91  0.05467   10.60
2        0.3182     0.04768   5708.0   1.065     0.91  0.05467   10.60
3        0.5400     0.00739   5837.0   1.510     1.13  0.39445    6.92
4        0.0500     0.02181   5825.0   1.490     1.08  0.39445    6.46
5        0.7500     0.00938   5825.0   1.490     1.08  0.39445    6.46
...         ...         ...      ...     ...      ...      ...     ...
8046        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8047        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8048        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8049        NaN         NaN      NaN     NaN      NaN      NaN     NaN
8050        NaN         NaN      NaN     NaN      NaN      NaN     NaN

      st_dens     _merge
1       1.068       both
2       1.068       both
3       0.440       both
4       0.440       both
5       0.440       both
...       ...        ...
8046      NaN  left_only
8047      NaN  left_only
8048      NaN  left_only
8049      NaN  left_only
8050      NaN  left_only

[8036 rows x 50 columns]